targets = ["//:concept_check"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.22.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.22.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.22.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.22.0"